import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/AppSidebar";
import { cookies } from "next/headers";
import getClient from "./lib/mongodb";

const ubuntu = Ubuntu({
  variable: "--font-ubuntu",
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Local",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";
  const client = await getClient();
  const db = client.db("bro-code");
  const collection = db.collection("Chat");
  const items = await collection.find(
    {},
    {
      projection: {
        _id: { $toString: "$_id" },
        "Chat.title": 1,
      },
    }
  ).toArray();
  const finalItems = items.map((item: any) => ({
    title: item.Chat.title,
    id: item._id,
  }));

  return (
    <html lang="en">
      <body className={`${ubuntu.variable}  antialiased`}>
        <SidebarProvider defaultOpen={defaultOpen}>
          <AppSidebar prop={finalItems} />
          <main>
            <SidebarTrigger />
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
